#!/usr/bin/env python3
"""Generate or validate harness outputs for the canonical repository skills.

Canonical skills live under ``.agents/skills/<skill-name>/SKILL.md``. This script
derives everything else from them:

- ``.claude/skills/<skill-name>/SKILL.md``: a portable text adapter per skill.
- ``.agents/skills/CATALOG.md``: a grouped, human-readable index.
- ``.agents/skills.lock``: per-skill content hashes used to detect drift, plus the
  shared-skill source recorded by ``scripts/update_shared_skills.py``.

``--check`` validates all of the above without writing, and also validates the
``_notes`` filename convention.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path


DEFAULT_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_RELATIVE_PATH = "scripts/sync_skills.py"
GENERATED_MARKER = f"Generated by {SCRIPT_RELATIVE_PATH}. Do not edit."
# Markers written by earlier versions of this tooling; still treated as generated so
# that upgrading the tooling can replace them.
LEGACY_GENERATED_MARKERS = ("Generated by scripts/sync_claude_skills.py. Do not edit.",)
LOCK_RELATIVE_PATH = ".agents/skills.lock"
CATALOG_RELATIVE_PATH = ".agents/skills/CATALOG.md"

SKILL_NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
GROUP_PATTERN = SKILL_NAME_PATTERN
TOP_LEVEL_FIELD_PATTERN = re.compile(r"^([A-Za-z0-9_-]+):(?:[ \t]+(.*))?$")
NESTED_FIELD_PATTERN = re.compile(r"^[ \t]+([A-Za-z0-9_-]+):(?:[ \t]+(.*))?$")
HANGUL_PATTERN = re.compile(r"[\u1100-\u11ff\u3130-\u318f\uac00-\ud7af]")

ORIGINS = ("shared", "local")

# Top-level frontmatter keys accepted in a canonical SKILL.md. ``name``,
# ``description`` and ``metadata`` follow the Agent Skills specification. The
# remaining keys are harness-specific options that Claude Code understands and
# other harnesses ignore; they are copied verbatim into the generated adapter.
CORE_KEYS = {"name", "description", "metadata"}
HARNESS_PASSTHROUGH_KEYS = {
    "license",
    "compatibility",
    "allowed-tools",
    "argument-hint",
    "disable-model-invocation",
    "user-invocable",
    "model",
}
ALLOWED_TOP_LEVEL_KEYS = CORE_KEYS | HARNESS_PASSTHROUGH_KEYS

# Local, regenerable content that must not influence a skill's content hash and
# must never be copied between repositories.
HASH_IGNORED_DIRECTORIES = {
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "node_modules",
    "_generated",
}
HASH_IGNORED_SUFFIXES = {".pyc", ".pyo", ".tmp"}
HASH_IGNORED_FILES = {".DS_Store", "Thumbs.db"}
# Only these UTF-8 text formats have checkout line endings normalised for hashing.
# Unknown formats and binary assets remain byte-exact.
TEXT_SUFFIXES = {".md", ".txt", ".py", ".sh", ".ps1", ".json", ".yaml", ".yml",
                 ".toml", ".lock", ".html", ".css", ".js", ".ts", ".svg"}
TEXT_FILENAMES = {".gitignore", ".gitattributes", ".editorconfig"}

NOTE_FILENAME_PATTERN = re.compile(r"^\d{6}-\d{4}-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
NOTE_RESERVED_SLUGS = {"readme", "con", "prn", "aux", "nul"} | {
    f"{prefix}{digit}" for prefix in ("com", "lpt") for digit in range(10)
}
NOTE_DIRECTORIES = (
    "_notes/grills",
    "_notes/handoffs/to_codex",
    "_notes/handoffs/to_claude",
    "_notes/handoffs/to_human",
)


class LayoutError(ValueError):
    """Raised when the shared skill layout violates the template contract."""


@dataclass(frozen=True)
class Skill:
    directory_name: str
    name: str
    description: str
    group: str
    origin: str
    frontmatter: str
    metadata: dict[str, str] = field(default_factory=dict)


# --------------------------------------------------------------------------- parsing


def parse_yaml_scalar(raw_value: str, field_name: str, path: Path) -> str:
    """Parse the small one-line scalar subset required by this template."""
    value = raw_value.strip()
    if not value or value in {"|", "|-", "|+", ">", ">-", ">+"}:
        raise LayoutError(f"{path}: {field_name} must be a non-empty one-line YAML scalar")

    if value.startswith('"'):
        decoder = json.JSONDecoder()
        try:
            parsed, end = decoder.raw_decode(value)
        except json.JSONDecodeError as error:
            raise LayoutError(f"{path}: invalid double-quoted {field_name}: {error}") from error
        if not isinstance(parsed, str):
            raise LayoutError(f"{path}: {field_name} must be a string")
        remainder = value[end:]
        if remainder.strip() and not re.fullmatch(r"[ \t]+#.*", remainder):
            raise LayoutError(f"{path}: unexpected content after {field_name}")
        return parsed

    if value.startswith("'"):
        index = 1
        characters: list[str] = []
        while index < len(value):
            if value[index] != "'":
                characters.append(value[index])
                index += 1
                continue
            if index + 1 < len(value) and value[index + 1] == "'":
                characters.append("'")
                index += 2
                continue
            remainder = value[index + 1 :]
            if remainder.strip() and not re.fullmatch(r"[ \t]+#.*", remainder):
                raise LayoutError(f"{path}: unexpected content after {field_name}")
            return "".join(characters)
        raise LayoutError(f"{path}: unterminated single-quoted {field_name}")

    comment_match = re.search(r"[ \t]+#", value)
    if comment_match:
        value = value[: comment_match.start()].rstrip()
    if not value:
        raise LayoutError(f"{path}: {field_name} must not be empty")
    if (value[0] in "[]{}&*!|>@`#%" or re.search(r":(?:\s|$)", value)
            or re.match(r"[-?:](?:\s|$)", value)
            or value.lower() in {"null", "~", "true", "false", "yes", "no", "on", "off", ".nan", ".inf", "-.inf", "+.inf"}
            or re.match(r"^[+-]?(?:\d|\.\d)", value)):
        raise LayoutError(f"{path}: quote {field_name}; unsupported or non-string YAML scalar")
    return value


def _is_block_scalar_indicator(raw_value: str) -> bool:
    return re.fullmatch(r"[>|][+-]?(?:[ \t]+#[^\r\n]*)?", raw_value.strip()) is not None


def _collect_block_lines(lines: list[str], start: int, end: int) -> list[str]:
    collected: list[str] = []
    for line in lines[start:end]:
        if line and not line[0].isspace():
            break
        if line.strip():
            collected.append(line.strip())
    return collected


def read_skill(skill_file: Path) -> Skill:
    text = skill_file.read_text(encoding="utf-8")
    if "\x00" in text:
        raise LayoutError(f"{skill_file}: NUL bytes are not allowed")

    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise LayoutError(f"{skill_file}: SKILL.md must start with YAML frontmatter")

    try:
        closing_index = next(
            index for index, line in enumerate(lines[1:], start=1) if line == "---"
        )
    except StopIteration as error:
        raise LayoutError(f"{skill_file}: YAML frontmatter is not closed") from error

    if not any(line.strip() for line in lines[closing_index + 1 :]):
        raise LayoutError(f"{skill_file}: instruction body must not be empty")

    raw_fields: dict[str, tuple[str, int]] = {}
    for index, line in enumerate(lines[1:closing_index], start=1):
        if not line or line[0].isspace() or line.lstrip().startswith("#"):
            continue
        match = TOP_LEVEL_FIELD_PATTERN.fullmatch(line)
        if not match:
            raise LayoutError(f"{skill_file}: unrecognised frontmatter line: {line!r}")
        field_name, raw_value = match.groups()
        if field_name not in ALLOWED_TOP_LEVEL_KEYS:
            allowed = ", ".join(sorted(ALLOWED_TOP_LEVEL_KEYS))
            raise LayoutError(
                f"{skill_file}: unsupported frontmatter field {field_name!r}; "
                f"allowed fields: {allowed}"
            )
        if field_name in raw_fields:
            raise LayoutError(f"{skill_file}: duplicate frontmatter field {field_name!r}")
        raw_fields[field_name] = (raw_value or "", index)

    missing = {"name", "description", "metadata"} - raw_fields.keys()
    if missing:
        names = ", ".join(sorted(missing))
        raise LayoutError(f"{skill_file}: missing frontmatter field(s): {names}")

    # Validate the whole supported subset, not just the fields we consume.
    # Scalar continuations, flow collections and arbitrary nested maps are excluded.
    owner = None
    block_indent = None
    for line in lines[1:closing_index]:
        if "\t" in line or any(ord(char) < 32 for char in line):
            raise LayoutError(f"{skill_file}: control characters are not allowed in frontmatter")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line[0].isspace():
            owner = TOP_LEVEL_FIELD_PATTERN.fullmatch(line).group(1)
            block_indent = None
            continue
        if owner == "metadata":
            if not re.fullmatch(r"  [A-Za-z0-9_-]+:.*", line):
                raise LayoutError(f"{skill_file}: metadata requires flat entries indented by two spaces")
        elif owner == "description" and _is_block_scalar_indicator(raw_fields[owner][0]):
            indent = len(line) - len(line.lstrip(" "))
            if block_indent is None:
                block_indent = indent
            if indent < block_indent:
                raise LayoutError(f"{skill_file}: inconsistent description block indentation")
        else:
            raise LayoutError(f"{skill_file}: unsupported indented frontmatter content")
    for key in HARNESS_PASSTHROUGH_KEYS & raw_fields.keys():
        raw = raw_fields[key][0]
        if key in {"disable-model-invocation", "user-invocable"}:
            if not re.fullmatch(r"(?:true|false)(?:[ \t]+#.*)?", raw.strip()):
                raise LayoutError(f"{skill_file}: {key} must be true or false")
        else:
            parse_yaml_scalar(raw, key, skill_file)

    name = parse_yaml_scalar(raw_fields["name"][0], "name", skill_file)

    raw_description, description_index = raw_fields["description"]
    if _is_block_scalar_indicator(raw_description):
        description_lines = _collect_block_lines(lines, description_index + 1, closing_index)
        if not description_lines:
            raise LayoutError(f"{skill_file}: description block must not be empty")
        description = " ".join(description_lines)
    else:
        description = parse_yaml_scalar(raw_description, "description", skill_file)
        if not description.strip():
            raise LayoutError(f"{skill_file}: description must not be empty")
    if HANGUL_PATTERN.search(description):
        raise LayoutError(
            f"{skill_file}: description must be written in English; "
            "put Korean glosses in the skill body or references instead"
        )

    raw_metadata, metadata_index = raw_fields["metadata"]
    if raw_metadata.strip() and not raw_metadata.strip().startswith("#"):
        raise LayoutError(f"{skill_file}: metadata must be a YAML mapping")
    metadata: dict[str, str] = {}
    for line in lines[metadata_index + 1 : closing_index]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line[0].isspace():
            break
        match = NESTED_FIELD_PATTERN.fullmatch(line)
        if not match:
            raise LayoutError(f"{skill_file}: metadata entries must be `key: value` lines")
        key, raw_value = match.groups()
        parse_yaml_scalar(key, "metadata key", skill_file)
        if key in metadata:
            raise LayoutError(f"{skill_file}: duplicate metadata field {key!r}")
        metadata[key] = parse_yaml_scalar(raw_value or "", f"metadata.{key}", skill_file)

    missing_metadata = {"group", "origin"} - metadata.keys()
    if missing_metadata:
        names = ", ".join(sorted(missing_metadata))
        raise LayoutError(f"{skill_file}: missing metadata field(s): {names}")
    group = metadata["group"]
    origin = metadata["origin"]
    if not GROUP_PATTERN.fullmatch(group):
        raise LayoutError(
            f"{skill_file}: metadata.group must contain only lowercase letters, digits, and hyphens"
        )
    if origin not in ORIGINS:
        raise LayoutError(f"{skill_file}: metadata.origin must be one of: {', '.join(ORIGINS)}")

    if not SKILL_NAME_PATTERN.fullmatch(name):
        raise LayoutError(
            f"{skill_file}: name must contain only lowercase letters, digits, and hyphens"
        )
    if skill_file.parent.name != name:
        raise LayoutError(
            f"{skill_file}: directory {skill_file.parent.name!r} must match name {name!r}"
        )
    return Skill(
        directory_name=skill_file.parent.name,
        name=name,
        description=description,
        group=group,
        origin=origin,
        frontmatter="\n".join(lines[1:closing_index]),
        metadata=metadata,
    )


def reject_symlink(path: Path) -> None:
    try:
        attributes = path.lstat()
    except FileNotFoundError:
        return
    if path.is_symlink() or getattr(attributes, "st_file_attributes", 0) & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400):
        raise LayoutError(f"symlinks are not portable and are not allowed here: {path}")


def safe_path(root: Path, path: Path) -> None:
    """Reject links/reparse points in every component, including missing leaf paths."""
    relative = path.relative_to(root)
    if ".." in relative.parts:
        raise LayoutError(f"path escapes repository: {path}")
    current = root
    reject_symlink(current)
    for part in relative.parts:
        if current.exists() and not current.is_dir():
            raise LayoutError(f"parent is not a directory: {current}")
        current = current / part
        reject_symlink(current)


def discover_skills(canonical_root: Path) -> list[Skill]:
    if not canonical_root.is_dir():
        raise LayoutError(f"canonical skill directory is missing: {canonical_root}")
    reject_symlink(canonical_root)

    skills: list[Skill] = []
    for path in sorted(canonical_root.iterdir(), key=lambda item: item.name):
        reject_symlink(path)
        if not path.is_dir() or path.name.startswith("."):
            continue
        skill_file = path / "SKILL.md"
        reject_symlink(skill_file)
        if not skill_file.is_file():
            raise LayoutError(f"canonical skill directory is missing SKILL.md: {path}")
        skills.append(read_skill(skill_file))
    return skills


# --------------------------------------------------------------------------- hashing


def is_hash_ignored(relative_path: Path) -> bool:
    parts = relative_path.parts
    if any(part in HASH_IGNORED_DIRECTORIES for part in parts[:-1]):
        return True
    if parts and parts[-1] in HASH_IGNORED_DIRECTORIES:
        return True
    if relative_path.name in HASH_IGNORED_FILES:
        return True
    return relative_path.suffix.lower() in HASH_IGNORED_SUFFIXES


def iter_skill_files(skill_directory: Path) -> list[Path]:
    """Return the content-bearing files of a skill, relative to its directory."""
    reject_symlink(skill_directory)
    files: list[Path] = []
    def walk(directory: Path) -> None:
        for path in sorted(directory.iterdir()):
            relative = path.relative_to(skill_directory)
            if is_hash_ignored(relative):
                continue
            reject_symlink(path)
            if path.is_dir():
                walk(path)
            elif path.is_file():
                files.append(relative)
            else:
                raise LayoutError(f"not a regular skill file: {path}")
    walk(skill_directory)
    return sorted(files)


def hash_bytes(path: Path) -> bytes:
    content = path.read_bytes()
    if path.suffix.lower() in TEXT_SUFFIXES or path.name in TEXT_FILENAMES:
        try:
            content.decode("utf-8")
        except UnicodeDecodeError:
            return content
        if b"\0" not in content:
            return content.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return content


def skill_content_hash(skill_directory: Path) -> str:
    digest = hashlib.sha256()
    for relative in iter_skill_files(skill_directory):
        digest.update(relative.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(hash_bytes(skill_directory / relative))
        digest.update(b"\0")
    return digest.hexdigest()


# --------------------------------------------------------------------------- generation


def adapter_content(skill: Skill) -> str:
    canonical_path = f".agents/skills/{skill.directory_name}/SKILL.md"
    return f"""---
{skill.frontmatter}
---

<!-- {GENERATED_MARKER} -->

# Shared skill adapter

Read `{canonical_path}` (path relative to the repository root) completely and follow
it as the canonical instructions for this skill. Resolve relative resource paths from
the canonical skill directory `.agents/skills/{skill.directory_name}/`.

Invocation arguments supplied through Claude Code:

$ARGUMENTS

Do not edit this adapter. Edit `{canonical_path}` and run
the repository's `{SCRIPT_RELATIVE_PATH}` instead.
"""


def catalog_content(skills: list[Skill]) -> str:
    lines = [
        "# Skill catalog",
        "",
        f"<!-- {GENERATED_MARKER} -->",
        "",
        "Canonical skills under `.agents/skills`, grouped by `metadata.group`. Origin",
        "`shared` skills are maintained in the template repository and refreshed with",
        "`scripts/update_shared_skills.py`; origin `local` skills belong to this repository.",
        "",
    ]
    if not skills:
        lines.append("No skills are defined yet.")
        lines.append("")
        return "\n".join(lines)

    groups: dict[str, list[Skill]] = {}
    for skill in skills:
        groups.setdefault(skill.group, []).append(skill)
    for group in sorted(groups):
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| Skill | Origin | Description |")
        lines.append("| --- | --- | --- |")
        for skill in sorted(groups[group], key=lambda item: item.name):
            description = skill.description.replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| [`{skill.name}`]({skill.directory_name}/SKILL.md) | {skill.origin} | {description} |"
            )
        lines.append("")
    return "\n".join(lines)


def read_lock(repository_root: Path) -> dict:
    lock_path = repository_root / LOCK_RELATIVE_PATH
    safe_path(repository_root, lock_path)
    if not lock_path.is_file():
        return {}
    try:
        data = json.loads(lock_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise LayoutError(f"{lock_path}: invalid JSON: {error}") from error
    if not isinstance(data, dict):
        raise LayoutError(f"{lock_path}: expected a JSON object")
    return data


def lock_content(repository_root: Path, skills: list[Skill], previous: dict) -> str:
    data: dict = {
        "generated_by": SCRIPT_RELATIVE_PATH,
        "skills": {
            skill.name: {
                "origin": skill.origin,
                "group": skill.group,
                "sha256": skill_content_hash(
                    repository_root / ".agents" / "skills" / skill.directory_name
                ),
            }
            for skill in skills
        },
    }
    if isinstance(previous.get("shared_source"), dict):
        data["shared_source"] = previous["shared_source"]
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def expected_outputs(repository_root: Path, skills: list[Skill]) -> dict[Path, str]:
    """Every generated file and its expected content."""
    claude_root = repository_root / ".claude" / "skills"
    outputs = {
        claude_root / skill.directory_name / "SKILL.md": adapter_content(skill)
        for skill in skills
    }
    outputs[repository_root / CATALOG_RELATIVE_PATH] = catalog_content(skills)
    outputs[repository_root / LOCK_RELATIVE_PATH] = lock_content(
        repository_root, skills, read_lock(repository_root)
    )
    return outputs


def expected_adapters(repository_root: Path, skills: list[Skill]) -> dict[Path, str]:
    claude_root = repository_root / ".claude" / "skills"
    return {
        claude_root / skill.directory_name / "SKILL.md": adapter_content(skill)
        for skill in skills
    }


# --------------------------------------------------------------------------- inspection


def existing_adapter_files(claude_root: Path) -> set[Path]:
    if not claude_root.is_dir():
        raise LayoutError(f"Claude skill directory is missing: {claude_root}")
    reject_symlink(claude_root)

    adapter_files: set[Path] = set()
    for relative in iter_skill_files(claude_root):
        path = claude_root / relative
        if path.name != "SKILL.md":
            continue
        reject_symlink(path)
        reject_symlink(path.parent)
        if not path.is_file():
            continue
        if path.parent.parent != claude_root:
            raise LayoutError(f"Claude adapters must be direct child directories: {path}")
        adapter_files.add(path)
    return adapter_files


def is_generated(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    return GENERATED_MARKER in text or any(marker in text for marker in LEGACY_GENERATED_MARKERS)


def inspect_adapters(
    repository_root: Path, expected: dict[Path, str]
) -> tuple[list[str], set[Path]]:
    claude_root = repository_root / ".claude" / "skills"
    existing = existing_adapter_files(claude_root)
    problems: list[str] = []

    for path, content in expected.items():
        relative = path.relative_to(repository_root)
        if path not in existing:
            problems.append(f"missing adapter: {relative}")
        elif not is_generated(path):
            problems.append(f"manual adapter conflicts with canonical skill: {relative}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"outdated adapter: {relative}")

    for path in sorted(existing - expected.keys()):
        relative = path.relative_to(repository_root)
        kind = "stale adapter" if is_generated(path) else "unmanaged Claude skill"
        problems.append(f"{kind}: {relative}")

    return problems, existing


def inspect_catalog(repository_root: Path, skills: list[Skill]) -> list[str]:
    catalog_path = repository_root / CATALOG_RELATIVE_PATH
    if not catalog_path.is_file():
        return [f"missing catalog: {CATALOG_RELATIVE_PATH}"]
    if catalog_path.read_text(encoding="utf-8") != catalog_content(skills):
        return [f"outdated catalog: {CATALOG_RELATIVE_PATH}"]
    return []


def inspect_lock(repository_root: Path, skills: list[Skill]) -> list[str]:
    lock = read_lock(repository_root)
    if not lock:
        return [f"missing lock file: {LOCK_RELATIVE_PATH}"]
    locked_skills = lock.get("skills")
    if not isinstance(locked_skills, dict):
        return [f"invalid lock file: {LOCK_RELATIVE_PATH} has no 'skills' object"]

    problems: list[str] = []
    for skill in skills:
        entry = locked_skills.get(skill.name)
        current = skill_content_hash(repository_root / ".agents" / "skills" / skill.directory_name)
        if not isinstance(entry, dict):
            problems.append(f"skill not in lock file: {skill.name}")
            continue
        drifted = (
            entry.get("sha256") != current
            or entry.get("origin") != skill.origin
            or entry.get("group") != skill.group
        )
        if not drifted:
            continue
        if skill.origin == "shared":
            problems.append(
                f"shared skill differs from lock file: {skill.name} "
                "(intentional edit in the template repository: run "
                f"{SCRIPT_RELATIVE_PATH}; accidental edit downstream: restore with "
                "scripts/update_shared_skills.py)"
            )
        else:
            problems.append(f"local skill differs from lock file: {skill.name}")

    known = {skill.name for skill in skills}
    for name in sorted(set(locked_skills) - known):
        problems.append(f"lock file lists a removed skill: {name}")
    return problems


def inspect_notes(repository_root: Path) -> list[str]:
    problems: list[str] = []
    for relative_directory in NOTE_DIRECTORIES:
        directory = repository_root / relative_directory
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.is_dir() or path.name == "README.md":
                continue
            relative = path.relative_to(repository_root)
            if not NOTE_FILENAME_PATTERN.fullmatch(path.name):
                problems.append(
                    f"note filename must match yymmdd-hhmm-<topic-slug>.md: {relative}"
                )
                continue
            slug = path.name[12:-3]
            if slug in NOTE_RESERVED_SLUGS or slug.split("-")[0] in NOTE_RESERVED_SLUGS:
                problems.append(f"note filename uses a reserved slug: {relative}")
    return problems


# --------------------------------------------------------------------------- commands


def atomic_write(path: Path, content: str) -> None:
    atomic_write_bytes(path, content.encode("utf-8"))


def atomic_write_bytes(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(content)
            temporary_name = temporary_file.name
        if path.is_file():
            os.chmod(temporary_name, stat.S_IMODE(path.stat().st_mode))
        os.replace(temporary_name, path)
        temporary_name = None
    finally:
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def apply_changes(root: Path, changes: dict[Path, bytes | None]) -> None:
    """Preflight all paths, then restore file contents on a caught write failure.

    Not crash-atomic: callers must not run concurrent writers. Rollback failures are
    reported explicitly; process termination or a persistent disk fault needs recovery.
    """
    originals = {}
    original_modes = {}
    new_directories: set[Path] = set()
    for path in changes:
        safe_path(root, path)
        if path.exists() and not path.is_file():
            raise LayoutError(f"file/directory conflict: {path}")
        originals[path] = path.read_bytes() if path.exists() else None
        if path.exists():
            original_modes[path] = stat.S_IMODE(path.stat().st_mode)
        parent = path.parent
        while parent != root and not parent.exists():
            new_directories.add(parent)
            parent = parent.parent
    applied = []
    try:
        for path, content in changes.items():
            safe_path(root, path)
            applied.append(path)
            if content is None:
                path.unlink(missing_ok=True)
            else:
                atomic_write_bytes(path, content)
    except (OSError, ValueError) as error:
        failures = []
        for path in reversed(applied):
            try:
                safe_path(root, path)
                original = originals[path]
                if original is None:
                    path.unlink(missing_ok=True)
                else:
                    atomic_write_bytes(path, original)
                    os.chmod(path, original_modes[path])
            except (OSError, ValueError) as rollback_error:
                failures.append(f"{path}: {rollback_error}")
        for directory in sorted(new_directories, key=lambda path: len(path.parts), reverse=True):
            try:
                directory.rmdir()
            except FileNotFoundError:
                pass
            except OSError as rollback_error:
                failures.append(f"{directory}: {rollback_error}")
        if failures:
            raise LayoutError(f"write failed ({error}); rollback incomplete: {'; '.join(failures)}") from error
        raise


def sync(repository_root: Path, skills: list[Skill]) -> int:
    adapters = expected_adapters(repository_root, skills)
    _, existing = inspect_adapters(repository_root, adapters)

    manual_files = [path for path in existing if not is_generated(path)]
    if manual_files:
        for path in sorted(manual_files):
            relative = path.relative_to(repository_root)
            print(f"error: refusing to overwrite unmanaged file: {relative}", file=sys.stderr)
        print("Move these skills into .agents/skills before syncing.", file=sys.stderr)
        return 1

    # Compute/validate everything before removing even a stale generated adapter.
    outputs = expected_outputs(repository_root, skills)
    changes: dict[Path, bytes | None] = {}
    for path, content in outputs.items():
        safe_path(repository_root, path)
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        changes[path] = content.encode("utf-8")
    for path in sorted(existing - adapters.keys()):
        changes[path] = None
    apply_changes(repository_root, changes)
    for path, content in changes.items():
        print(f"{'Removed' if content is None else 'Updated'} {path.relative_to(repository_root)}")

    for problem in inspect_notes(repository_root):
        print(f"warning: {problem}", file=sys.stderr)

    if not changes:
        print("Skill outputs are already current.")
    return 0


def check(repository_root: Path, skills: list[Skill]) -> int:
    problems, _ = inspect_adapters(repository_root, expected_adapters(repository_root, skills))
    problems += inspect_catalog(repository_root, skills)
    problems += inspect_lock(repository_root, skills)
    problems += inspect_notes(repository_root)
    if problems:
        print("Skill check failed:", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        print(f"Run: python {SCRIPT_RELATIVE_PATH}", file=sys.stderr)
        return 1

    print(f"Skill outputs are current ({len(skills)} skill(s)).")
    return 0


def run(repository_root: Path, check_only: bool) -> int:
    try:
        for relative in (".agents/skills", ".claude/skills", CATALOG_RELATIVE_PATH, LOCK_RELATIVE_PATH):
            safe_path(repository_root, repository_root / relative)
        skills = discover_skills(repository_root / ".agents" / "skills")
        return check(repository_root, skills) if check_only else sync(repository_root, skills)
    except (LayoutError, OSError, UnicodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate generated outputs without changing files",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_REPOSITORY_ROOT,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args()
    return run(args.root.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
